package GUI;

import static com.lowagie.text.pdf.PdfName.P;
import static java.lang.Thread.sleep;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author akiba
 */
public class Accueil extends javax.swing.JFrame {

    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    Statement st;
    private Reception f;

    /**
     * Creates new form Accueil
     */
    public Accueil() {
        initComponents();
        datecourante();
    }

    public void datecourante() {
        Thread clock = new Thread() {
            public void run() {
                for (;;) {
                    Calendar cal = new GregorianCalendar();
                    int seconde = cal.get(Calendar.SECOND);
                    int minute = cal.get(Calendar.MINUTE);
                    int heure = cal.get(Calendar.HOUR);
                    LabHeure.setText("Heure : " + heure + ":" + minute + ":" + seconde);
                    try {
                        sleep(1000);

                    } catch (InterruptedException ex) {
                        Logger.getLogger(Calendar.class.getName()).log(Level.SEVERE, null, ex);

                    }
                }
            }
        };
        clock.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        LabHeure = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu13 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();

        jLabel4.setFont(new java.awt.Font("Lucida Sans", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(241, 19, 19));
        jLabel4.setText("CBCA NDOSHO");
        jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(246, 246, 246), 1, true));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Acceuil");
        setBackground(new java.awt.Color(0, 153, 153));
        setLocation(new java.awt.Point(0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 153, 153));
        jLabel1.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        jLabel1.setText("Acceuil");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 116, -1, -1));

        jPanel4.setBackground(new java.awt.Color(175, 202, 229));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/h.png"))); // NOI18N

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/h.png"))); // NOI18N

        LabHeure.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LabHeure.setText("Date Time");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 628, Short.MAX_VALUE)
                .addComponent(LabHeure, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106)
                .addComponent(jLabel15)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel15)
                        .addComponent(jLabel6))
                    .addComponent(LabHeure, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, -1));

        jLabel5.setBackground(new java.awt.Color(0, 153, 153));
        jLabel5.setForeground(new java.awt.Color(0, 153, 153));
        jLabel5.setToolTipText("");
        jLabel5.setFocusTraversalPolicyProvider(true);
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, 109, 1170, 540));

        jMenuBar1.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N

        jMenu1.setText("File");
        jMenu1.setFocusable(false);
        jMenu1.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N

        jMenu3.setText("Réception ");
        jMenu3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        jMenu4.setText("Nouvea Malade");
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenu4);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Liste de Malades");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenu1.add(jMenu3);

        jMenu5.setText("Consultation");
        jMenu5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jMenu6.setText("Ajouter une Consultation");
        jMenu5.add(jMenu6);

        jMenu7.setText("Liste de toutes les Consultations");
        jMenu5.add(jMenu7);

        jMenu1.add(jMenu5);

        jMenu8.setText("Hospitalisation");
        jMenu8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jMenu9.setText("Ajouter une Consommation");
        jMenu8.add(jMenu9);

        jMenu11.setText("Liste de Consommations");
        jMenu8.add(jMenu11);

        jMenu1.add(jMenu8);

        jMenu10.setText("Autils Administrateur");
        jMenu10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jMenu12.setText("Espace Admin");
        jMenu10.add(jMenu12);

        jMenu1.add(jMenu10);

        jMenuBar1.add(jMenu1);

        jMenu2.setBackground(new java.awt.Color(0, 191, 221));
        jMenu2.setBorder(new javax.swing.border.MatteBorder(null));
        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Capture.JPG"))); // NOI18N
        jMenu2.setText("Imprimer");
        jMenu2.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N

        jMenuItem2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jMenuItem2.setText("Facture");
        jMenu2.add(jMenuItem2);

        jMenuItem4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jMenuItem4.setText("Reçu de paiement");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jMenuItem5.setText("Liste de Médecins");
        jMenu2.add(jMenuItem5);

        jMenuItem6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jMenuItem6.setText("Fiche de consultation");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenu13.setText("Liste des malades");
        jMenu13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jMenuItem7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jMenuItem7.setText("Tous les Malades");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu13.add(jMenuItem7);

        jMenuItem8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jMenuItem8.setText("Malades hospitalisés");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu13.add(jMenuItem8);

        jMenu2.add(jMenu13);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        try {
            String url = "jdbc:mysql://localhost/gestionhospitaliere";
            con = DriverManager.getConnection(url, "root", "");
            System.out.println("Bien 1");
//         JasperDesign jDesign =JRXmlLoader.load("C:\\Users\\Djumbi\\Desktop\\ASSISTANT\\Java\\DataBase\\src\\L.jrxml");
            JasperDesign jDesign = JRXmlLoader.load("A:\\À_moi_jack\\G3_défense\\Projet\\GestionHospitaliere\\Rapports\\ListeMaladeH.jrxml");
            System.out.print("Bien");
            String query = "SELECT DISTINCT malade.`Id_Malade` AS malade_Id_Malade, malade.`Noms` AS malade_Noms, malade.`Sexe` AS malade_Sexe, interner.`Service` AS interner_Service, interner.`Statut` AS interner_Statut, chambre.`Description` AS chambre_Description, interner.`DEntree` AS interner_DEntree FROM `malade` malade INNER JOIN `interner` interner ON malade.`Id_Malade` = interner.`IdM` INNER JOIN `chambre` chambre ON interner.`IdChambre` = chambre.`Id`where interner.`Statut`='HOSPITALISE'ORDER BY Noms Asc";
            JRDesignQuery updateQuery = new JRDesignQuery();
            updateQuery.setText(query);
            jDesign.setQuery(updateQuery);
            JasperReport jReport = JasperCompileManager.compileReport(jDesign);
            System.out.println("Bien");
            JasperPrint jPrint = JasperFillManager.fillReport(jReport, null, con);
            JasperViewer.viewReport(jPrint);
        } catch (Exception ex) {
            Logger.getLogger(Accueil.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        try {
            String url = "jdbc:mysql://localhost/gestionhospitaliere";
            con = DriverManager.getConnection(url, "root", "");
            System.out.println("Bien 1");
//         JasperDesign jDesign =JRXmlLoader.load("C:\\Users\\Djumbi\\Desktop\\ASSISTANT\\Java\\DataBase\\src\\L.jrxml");
            JasperDesign jDesign = JRXmlLoader.load("A:\\À_moi_jack\\G3_défense\\Projet\\GestionHospitaliere\\src\\Reports\\ListeMalade.jrxml");
            System.out.print("Bien");
            String query = "SELECT `Id_Malade`, `Noms`, `Sexe`, `DateNaiss`, `Telephone`, `EtatCivil` FROM `malade`ORDER BY Noms Asc";

            JRDesignQuery updateQuery = new JRDesignQuery();
            updateQuery.setText(query);
            jDesign.setQuery(updateQuery);
            JasperReport jReport = JasperCompileManager.compileReport(jDesign);
            System.out.println("Bien");
            JasperPrint jPrint = JasperFillManager.fillReport(jReport, null, con);

            JasperViewer.viewReport(jPrint);
        } catch (Exception ex) {
            Logger.getLogger(Accueil.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        String n = JOptionPane.showInputDialog("Entre le numéro du Reçu ");
        int i = Integer.parseInt(n);
        try {
            String url = "jdbc:mysql://localhost/gestionhospitaliere";
            con = DriverManager.getConnection(url, "root", "");
            System.out.println("Bien 1");
//         JasperDesign jDesign =JRXmlLoader.load("C:\\Users\\Djumbi\\Desktop\\ASSISTANT\\Java\\DataBase\\src\\L.jrxml");
            JasperDesign jDesign = JRXmlLoader.load("A:\\À_moi_jack\\G3_défense\\Projet\\GestionHospitaliere\\Rapports\\Recu.jrxml");
            System.out.print("Bien");
            String query = " SELECT\n"
                    + "     perception.`IdP` AS perception_IdP,\n"
                    + "     perception.`IdM` AS perception_IdM,\n"
                    + "     perception.`Dpaiement` AS perception_Dpaiement,\n"
                    + "     perception.`Montant` AS perception_Montant,\n"
                    + "     perception.`Motif` AS perception_Motif,\n"
                    + "     perception.`Mlettre` AS perception_Mlettre,\n"
                    + "     malade.`Id_Malade` AS malade_Id_Malade,\n"
                    + "     malade.`Noms` AS malade_Noms,\n"
                    + "     malade.`Sexe` AS malade_Sexe,\n"
                    + "     malade.`Telephone` AS malade_Telephone\n"
                    + "FROM\n"
                    + "     `malade` malade INNER JOIN `perception` perception ON malade.`Id_Malade` = perception.`IdM` where IdP=" + n;

            JRDesignQuery updateQuery = new JRDesignQuery();
            updateQuery.setText(query);
            jDesign.setQuery(updateQuery);
            JasperReport jReport = JasperCompileManager.compileReport(jDesign);
            System.out.println("Bien");
            JasperPrint jPrint = JasperFillManager.fillReport(jReport, null, con);

            JasperViewer.viewReport(jPrint);
        } catch (Exception ex) {
            Logger.getLogger(Accueil.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed

    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
       

    }//GEN-LAST:event_jMenu4ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
         f = new Reception();
        f.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
     try {
            String url = "jdbc:mysql://localhost/gestionhospitaliere";
            con = DriverManager.getConnection(url, "root", "");
            System.out.println("Bien 1");
//         JasperDesign jDesign =JRXmlLoader.load("C:\\Users\\Djumbi\\Desktop\\ASSISTANT\\Java\\DataBase\\src\\L.jrxml");
            JasperDesign jDesign = JRXmlLoader.load("A:\\À_moi_jack\\G3_défense\\Projet\\GestionHospitaliere\\src\\Reports\\ListeMalade.jrxml");
            System.out.print("Bien");
            String query = "SELECT `Id_Malade`, `Noms`, `Sexe`, `DateNaiss`, `Telephone`, `EtatCivil` FROM `malade`ORDER BY Noms Asc";

            JRDesignQuery updateQuery = new JRDesignQuery();
            updateQuery.setText(query);
            jDesign.setQuery(updateQuery);
            JasperReport jReport = JasperCompileManager.compileReport(jDesign);
            System.out.println("Bien");
            JasperPrint jPrint = JasperFillManager.fillReport(jReport, null, con);

            JasperViewer.viewReport(jPrint);
        } catch (Exception ex) {
            Logger.getLogger(Accueil.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Accueil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabHeure;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
